name: Deploy to GitHub Pages and Update Stock Data

on:
  # Deploy on push to main
  push:
    branches: [ main ]
  
  # Monthly stock data update (1st of every month at 9 AM UTC)
  schedule:
    - cron: '0 9 1 * *'
  
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Update stock data (runs on schedule or manual trigger)
  update-stock-data:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Fetch stock data
      run: npm run fetch-stock-data
      env:
        ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/*.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update stock data - $(date)"
          git push
        fi

  # Build and deploy to GitHub Pages
  build-and-deploy:
    if: always() && (github.event_name == 'push' || needs.update-stock-data.result == 'success' || needs.update-stock-data.result == 'skipped')
    needs: [update-stock-data]
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
